import { vueInterventionEdit } from "./class_intervention_edit.js";

vueInterventionEdit.init({
  div_Titre : document.querySelector('[id=div_intervention_titre]')
  ,div_intervention_detail : document.querySelector('[id=div_intervention_detail]')
  ,edt_intervention_num : document.querySelector('[id=edt_intervention_num]')
  ,edt_intervention_date : document.querySelector('[id=edt_intervention_date]')
  ,edt_presta_qte : document.querySelector('[id=edt_presta_qte]')
  ,lbl_erreur_contrat : document.querySelector('[id=lbl_erreur_contrat]')
  ,edt_intervention_numcontrat : document.querySelector('[id=edt_intervention_numcontrat]')
  ,lbl_erreur_presta : document.querySelector('[id=lbl_erreur_presta]')
  ,btn_intervention_ajouter : document.querySelector('[id=btn_intervention_ajouter]')
  ,div_intervention_presta_edit : document.querySelector('[id=div_intervention_presta_edit]')
  ,div_intervention_rubrique : document.querySelector('[id=div_intervention_rubrique]')
  ,select_presta : document.querySelector('[id=select_presta]')
  ,lbl_erreur_select : document.querySelector('[id=lbl_erreur_presta]')
  ,lbl_erreur_qte : document.querySelector('[id=lbl_erreur_qte]')
  ,btn_presta_valider : document.querySelector('[id=btn_presta_valider]')
  ,btn_presta_annuler : document.querySelector('[id=btn_presta_annuler]')
  ,btn_intervention_retour : document.querySelector('[id=btn_intervention_retour]')
  ,btn_intervention_valider : document.querySelector('[id=btn_intervention_valider]')
  ,btn_intervention_annuler : document.querySelector('[id=btn_intervention_annuler]')
  ,lbl_intervention_site : document.querySelector('[id=lbl_intervention_site]')
  ,lbl_intervention_client : document.querySelector('[id=lbl_intervention_client]')
  ,intervention_motif : document.querySelector('[id=intervention_motif]')
  ,intervention_obs : document.querySelector('[id=intervention_obs]')
  ,table_presta : document.querySelector('[id=table_presta]')
  ,lbl_prestation_total : document.querySelector('[id=lbl_prestation_total]')
  ,lbl_erreur_motif : document.querySelector('[id=lbl_erreur_motif]')
});
